Online_learning_platform/educa/chat/urls.py
from django.urls import path
from . import views

app_name = 'chat'

urlpatterns = [
    path('room/<int:course_id>/', views.course_chat_room,
         name='course_chat_room'),
]

Online_learning_platform/educa/courses/api/urls.py
from django.urls import path, include
from rest_framework import routers
from . import views

app_name = 'courses'         # имя приложения к которому относится api

router = routers.DefaultRouter() # обьект маршрутизатор генерирует авто url для Viewset
router.register('courses', views.CourseViewSet) # обьект Viewset



urlpatterns = [
    path('subjects/', views.SubjectListView.as_view(),
         name='subject_list'),
    path('subjects/<pk>/', views.SubjectDetailView.as_view(),
         name='subject_detail'),
    path('', include(router.urls)), # базовая страница api

]

Online_learning_platform/educa/courses/urls.py
from django.urls import path, include # import model for url templates
from . import views  # импортируем все классы

urlpatterns = [
    path('mine/', views.ManageCourseListView.as_view(),
         name='manage_course_list'),
    path('create/', views.CourseCreateView.as_view(),
         name='course_create'),
    path('<pk>/edit/', views.CourseUpdateView.as_view(),
         name='course_edit'),
    path('<pk>/delete/',
         views.CourseDeleteView.as_view(),
         name='course_delete'),
    path('<pk>/module/', views.CourseModuleUpdateView.as_view(),
         name='course_module_update'),
    path('module/<int:module_id>/content/<model_name>/create/',
         views.ContentCreateUpdateView.as_view(),
         name='module_content_create'),
    path('module/<int:module_id>/content/<model_name>/<id>/',
         views.ContentCreateUpdateView.as_view(),
         name='module_content_update'),
    path('content/<int:id>/delete/',
         views.ContentDeleteView.as_view(),
         name='module_content_delete'),
    path('module/<int:module_id>/',
         views.ModuleContentListView.as_view(),
         name='module_content_list'),
    path('module/order/', views.ModuleOrderView.as_view(),
         name='module_order'),
    path('content/order/', views.ContentOrderView.as_view(),
         name='content_order'),
    path('subject/<slug:subject>', views.CourseListView.as_view(),
         name='course_list_subject'),   # отображаем все курсы предмета
    path('<slug:slug>', views.CourseDetailView.as_view(),
         name='course_detail'),  # отображаем детальную информацию о курсе
    path('__debug__/', include('debug_toolbar.urls')), # отображение дебагера

]

Online_learning_platform/educa/courses/models.py
from django.db import models
from django.contrib.auth.models import User
from django.contrib.contenttypes.models import ContentType
from django.contrib.contenttypes.fields import GenericForeignKey
from .fields import OrderField
from django.template.loader import render_to_string # импортируем функцию которая прорисовывает шаблон
                                                    # и возвращает прорисовонное содержимое ввиде строкового литерала




class Subject(models.Model):
    title = models.CharField(max_length=200)
    slug = models.SlugField(max_length=200, unique=True)

    class Meta:
        ordering = ['title']

    def __str__(self):
        return self.title


class Course(models.Model):
    owner = models.ForeignKey(User,
                              related_name='courses_created',
                              on_delete=models.CASCADE)
    subject = models.ForeignKey(Subject,
                                related_name='courses',
                                on_delete=models.CASCADE)
    title = models.CharField(max_length=200)
    slug = models.SlugField(max_length=200, unique=True)
    overview = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    students = models.ManyToManyField(User,  # поля для отношения многим ко многим курсов со студентами
                                      related_name='courses_joined',
                                      blank=True)

    class Meta:
        ordering = ['-created']

    def __str__(self):
        return self.title


class Module(models.Model):
    course = models.ForeignKey(Course,
                               related_name='modules',
                               on_delete=models.CASCADE)
    title = models.CharField(max_length=200)
    description = models.TextField(blank=True)
    order = OrderField(blank=True, for_fields=['course'])

    class Meta:
        ordering = ['order']

    def __str__(self):
        return f'{self.order}. {self.title}'


class Content(models.Model):
    module = models.ForeignKey(Module,
                               related_name='contents',
                               on_delete=models.CASCADE)
    content_type = models.ForeignKey(ContentType,
                                     on_delete=models.CASCADE,
                                     limit_choices_to={'model__in':(
                                     'text',
                                     'video',
                                     'image',
                                     'file')})
    object_id = models.PositiveIntegerField()
    item = GenericForeignKey('content_type', 'object_id')
    order = OrderField(blank=True, for_fields=['module'])

    class Meta:
        ordering = ['order']


class ItemBase(models.Model):
    owner = models.ForeignKey(User,
                              related_name='%(class)s_related',
                              on_delete=models.CASCADE)
    title = models.CharField(max_length=250)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        abstract = True

    def __str__(self):
        return self.title

    def render(self):  # render общий интерфейс
        return render_to_string(
            f'courses/content/{self._meta.model_name}.html', # динамически создвёт имя шаблона
            {'item': self}
        )


class Text(ItemBase):
    content = models.TextField()


class File(ItemBase):
    file = models.FileField(upload_to='files')


class Image(ItemBase):
       file = models.FileField(upload_to='images')


class Video(ItemBase):
    url = models.URLField()

Online_learning_platform/educa/courses/forms.py
from django import forms
from django.forms.models import inlineformset_factory  # набор форм а не одна диниамическ
                                                       # для этого указываем первый класс родитель
                                                       # второй класс дочерний и за счет этого формы будут связанны
from .models import Course, Module

ModuleFormSet = inlineformset_factory(Course,
                                      Module,
                                      fields=['title',           # поля для формы
                                              'description'],
                                      extra=2,                   # устанавливае число доп форм
                                      can_delete=True            # устанавливаем True для каждой формы
                                      )

Online_learning_platform/educa/courses/api/views.py
from rest_framework import generics
from django.shortcuts import get_object_or_404
from rest_framework.views import APIView # надстройка апи над джанго drf
from rest_framework.response import Response
from courses.models import Subject, Course # класс к котрому будет доступ апи
from courses.api.serializers import SubjectSerializer, CourseSerializer  # класс api который будет работать
from rest_framework.authentication import BasicAuthentication # импортируем класс аутентийфикации
from rest_framework.permissions import IsAuthenticated # класс разрешений для пользоватлей
from rest_framework import viewsets # для создания набора представлений и маршрутизаторов
from rest_framework.decorators import action # импортируем функцию декоратор
from courses.api.permissions import IsEnrolled
from courses.api.serializers import CourseWithContentsSerializer
class SubjectListView(generics.ListAPIView):
    queryset = Subject.objects.all()
    serializer_class = SubjectSerializer


class SubjectDetailView(generics.RetrieveAPIView):
    queryset = Subject.objects.all()
    serializer_class = SubjectSerializer



class CourseViewSet(viewsets.ReadOnlyModelViewSet):
    queryset = Course.objects.all()
    serializer_class = CourseSerializer

    @action(
        detail=True,
        methods=['post'],
        authentication_classes=[BasicAuthentication],  # проверям аутентификацию
        permission_classes=[IsAuthenticated], # разрешния для авторизированых пользователей

    )
    def enroll(self, request, *args, **kwargs):
        course = self.get_object()
        course.students.add(request.user)
        return Response({'enrolled': True})


    @action(detail=True,
            methods=['get'],
            serializer_class=CourseWithContentsSerializer,
            authentication_classes=[BasicAuthentication],
            permission_classes=[IsAuthenticated, IsEnrolled])
    def contents(self, request, *args, **kwargs):
        return self.retrieve(request, *args, **kwargs)

Online_learning_platform/educa/courses/templates/courses/course/detail.html
{% extends "base.html" %}

{% block title %}
  {{ object.title }}
{% endblock %}

{% block content %}
  {% with subject=object.subject %}
    <h1>
      {{ object.title }}
    </h1>
    <div class="module">
      <h2>Overview</h2>
      <p>
        <a href="{% url 'course_list_subject' subject.slug %}">
        {{ subject.title }}</a>.
        {{ object.modules.count }} modules.
        Instructor: {{ object.owner.get_full_name }}
      </p>
      {{ object.overview|linebreaks }}
      {% if request.user.is_authenticated %}
        <form action="{% url 'student_enroll_course' %}" method="post">
          {{ enroll_form }}
          {% csrf_token %}
          <input type="submit" value="Enroll now">
        </form>
      {% else %}
        <a href="{% url 'student_registration' %}" class="button">
          Register to enroll
        </a>
      {% endif %}
    </div>
  {% endwith %}
{% endblock %}

Online_learning_platform/educa/courses/templates/courses/course/list.html
{% extends "base.html" %}

{% block title %}
  {% if subject %}
    {{ subject.title }} courses
  {% else %}
    All courses
  {% endif %}
{% endblock %}

{% block content %}
  <h1>
    {% if subject %}
      {{ subject.title }} courses
    {% else %}
      All courses
    {% endif %}
  </h1>
  <div class="contents">
    <h3>Subjects</h3>
    <ul id="modules">
      <li {% if not subject %}class="selected"{% endif %}>
        <a href="{% url 'course_list' %}">All</a>
      </li>
      {% for s in subjects %}
        <li {% if subject == s %}class="selected"{% endif %}>
          <a href="{% url 'course_list_subject' s.slug %}">
            {{ s.title }}
            <br>
            <span>{{ s.total_courses }} course{{ s.total_courses|pluralize }}</span>
          </a>
        </li>
      {% endfor %}
    </ul>
  </div>
  <div class="module">
    {% for course in courses %}
      {% with subject=course.subject %}
        <h3>
          <a href="{% url 'course_detail' course.slug %}">
            {{ course.title }}
          </a>
        </h3>
        <p>
          <a href="{% url 'course_list_subject' subject.slug %}">{{ subject }}</a>.
            {{ course.total_modules }} modules.
            Instructor: {{ course.owner.get_full_name }}
        </p>
      {% endwith %}
    {% endfor %}
  </div>
{% endblock %}