Online_Shop/myshop/cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:product_id>/', views.cart_add, name='cart_add'),
    path('remove/<int:product_id>/', views.cart_remove,
                                     name='cart_remove'),
]

Online_Shop/myshop/coupons/urls.py
from django.urls import path

from .import views

app_name = 'coupons'   # название приложения

urlpatterns = [
    path('apply/', views.coupon_apply, name='apply')
]

Online_Shop/myshop/myshop/urls.py
from django.contrib import admin
from django.urls import path, include  # добовляем модуль include
from django.conf import settings  # импортируем настройки
from django.conf.urls.static import static  # импортируем метод static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('cart/', include('cart.urls', namespace='cart')),
    path('orders/', include('orders.urls', namespace='orders')),
    path('coupons/', include('coupons.urls', namespace='coupons')),
    path('', include('shop.urls', namespace='shop')),  # включаем шаблоны приложения по имени приложения
]


# реализуем раздачу файлов через джанго
if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL,
        document_root=settings.MEDIA_ROOT)

Online_Shop/myshop/orders/urls.py
from django.urls import path
from . import views

app_name = 'orders'   # Create name app

urlpatterns = [
    path('',views.order_create, name='order_create' ),
    path('admin/order/<int:order_id>/', views.admin_order_detail,
                                        name='admin_order_detail'),
    path('admin/order/<int:order_id>/pdf', views.admin_order_pdf, name='admin_order_pdf'),
]

Online_Shop/myshop/shop/urls.py
from django.urls import path                    # импортируем библиотеку urls
from . import views                             # из этого же каталога ипортируем созданное
                                                # представлние обьектов на html странице

app_name = 'shop'  # создаём переменную присваеваем имя нашего приложения

# у path первый аргумент вид шаблона как будет отображатся, второй аргумент источник информации,
# третий аргумент имя шаблона по которому можно бдует к нему обращатся

urlpatterns = [                           # создаём шаблоны url адрессов для наших класс
    path('', views.product_list, name='product_list'),  # первый шаблон для списка без параметров
    path('<slug:category_slug>/', views.product_list,   # второй шаблон для списка с параметрами
         name='product_list_by_category'),
    path('<int:id>/<slug:slug>/', views.product_detail,
         name='product_detail')
]

Online_Shop/myshop/cart/forms.py
from django import forms  # импортируем формы джанго

PRODUCT_QUANTITY_CHOICES = [(i, str(i)) for i in range(1, 21)]


class CartAddProductForm(forms.Form):
    # Возможность добавления от 0 до 20
    quantity = forms.TypedChoiceField(choices=PRODUCT_QUANTITY_CHOICES,
                                      coerce=int)

    # Нужно ли добавить к существуещему количеству или добавить отдельно
    override = forms.BooleanField(required=False,
                                  initial=False,
                                  widget=forms.HiddenInput)

Online_Shop/myshop/cart/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST  # Post запросы так как карзина посылает запросы приложению
from shop.models import Product  # import Product (товара)
from .cart import Cart  # import Cart(корзины)
from .forms import CartAddProductForm  # import Form( формы корзины)
from coupons.forms import CouponApplyForm # преедставление купона в коризине
from shop.recommender import Recommender

# Create your views here.
@require_POST
def cart_add(request, product_id):
    """
    Процесс добавления в корзину
    :param request:
    :param product_id:
    :return:
    """
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    form = CartAddProductForm(request.POST)
    if form.is_valid():
        cd = form.cleaned_data
        cart.add(product=product,
                 quantity=cd['quantity'],
                 override_quantity=cd['override'])
    return redirect('cart:cart_detail') # перенаправление на url адресс cart_detail

@require_POST
def cart_remove(request, product_id):
    """
    Процес удаления из корзины
    :param request:
    :param product_id:
    :return:
    """
    card = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    card.remove(product)
    return redirect('cart:cart_detail')


def cart_detail(request):
    cart = Cart(request)
    for item in cart:
        item['update_quantity_form'] = CartAddProductForm(initial={
                            'quantity': item['quantity'],
                            'override': True})
    coupon_apply_form = CouponApplyForm()

    r = Recommender()
    cart_products = [item['product'] for item in cart]
    if(cart_products):
        recommended_products = r.suggest_products_for(cart_products,
                                                      max_results=4)
    else:
        recommended_products = []

    return render(request,
                  'cart/detail.html',
                  {'cart': cart,
                   'coupon_apply_form': coupon_apply_form,
                   'recommended_products': recommended_products})

Online_Shop/myshop/cart/templates/cart/detail.html
{% extends "shop/base.html" %}
{% load static %}

{% block title %}
  Your shopping cart
{% endblock %}

{% block content %}
  <h1>Your shopping cart</h1>
  <table class="cart">
    <thead>
      <tr>
        <th>Image</th>
        <th>Product</th>
        <th>Quantity</th>
        <th>Remove</th>
        <th>Unit price</th>
        <th>Price</th>
      </tr>
    </thead>
    <tbody>
      {% for item in cart %}
        {% with product=item.product %}
          <tr>
            <td>
              <a href="{{ product.get_absolute_url }}">
                <img src="{% if product.image %}{{ product.image.url }}
                {% else %}{% static 'img/no_image.png' %}{% endif %}">
              </a>
            </td>
            <td>{{ product.name }}</td>
            <td>
              <form action="{% url 'cart:cart_add' product.id %}" method="post">
                {{ item.update_quantity_form.quantity }}
                {{ item.update_quantity_form.override }}
                <input type="submit" value="Update">
                {% csrf_token %}
              </form>
            </td>
            <td>
              <form action="{% url 'cart:cart_remove' product.id %}" method="post">
                <input type="submit" value="Remove">
                {% csrf_token %}
              </form>
            </td>
            <td class="num">${{ item.price }}</td>
            <td class="num">${{ item.total_price }}</td>
          </tr>
        {% endwith %}
      {% endfor %}
      {% if cart.coupon %}
        <tr class="subtotal">
          <td>Subtotal</td>
          <td colspan="4"></td>
          <td class="num">${{ cart.get_total_price|floatformat:2 }}</td>
        </tr>
        <tr>
          <td>
            "{{ cart.coupon.code }}" coupon
            ({{ cart.coupon.discount }}% off)
          </td>
          <td colspan="4"></td>
          <td class="num neg">
             ${{ cart.get_discount }}
          </td>
        </tr>
      {% endif %}
      <tr class="total">
        <td>Total</td>
        <td colspan="4"></td>
        <td class="num">
          ${{ cart.get_total_price_after_discount|floatformat:2 }}
        </td>
      </tr>
    </tbody>
  </table>


  {% if recommended_products %}
  <div class="recommendations cart">
    <h3>People who bought this also bought</h3>
    {% for p in recommended_products %}
      <div class="item">
        <a href="{{ p.get_absolute_url }}">
          <img src="{% if p.image %}{{ p.image.url }}{% else %}
          {% static 'img/no_image.png' %}{% endif %}">
        </a>
        <p><a href="{{ p.get_absolute_url }}">{{ p.name }}</a></p>
      </div>
    {% endfor %}
  </div>
{% endif %}

  <p>Apply a coupon:</p>
  <form action="{% url 'coupons:apply' %}" method="post">
    {{ coupon_apply_form }}
    <input type="submit" value="Apply">
    {% csrf_token %}
  </form>
  <p class="text-right">
    <a href="{% url 'shop:product_list' %}" class="button
    light">Continue shopping</a>
    <a href="{% url 'orders:order_create' %}" class="button">Checkout</a>
  </p>
{% endblock %}